### ISSUE TITLE
厚工坊报错

### ISSUE THREAD

**Issue by huagemeinv** [zjk2017/ArcadiaScriptPublic#4]
🔔厚工坊, 开始!
共1个账号
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at safeGet (/ql/data/scripts/厚工坊.js:174:21)
    at /ql/data/scripts/厚工坊.js:112:15
    at /ql/data/scripts/厚工坊.js:194:5783
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
服务器访问数据为空，请检查自身设备网络情况

🔔厚工坊, 结束! 🕛 0.056 秒

**Comment by zjk2017** [comment]
仔细检查是不是抓错了 仔细看脚本前面描述 ，脚本描述已经更新了
